#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#
# Generated with:
#
# thrift --gen rb ./thrift/order.thrift

require 'thrift'

module Thrift
  class Order
    include ::Thrift::Struct, ::Thrift::Struct_Union
    A = 1
    B = 2
    C = 3
    D = 4
    E = 5
    F = 6
    G = 7
    H = 8
    I = 9
    J = 10
    K = 11
    L = 12
    M = 13
    N = 14
    O = 15

    FIELDS = {
      A => {:type => ::Thrift::Types::I32, :name => 'a'},
      B => {:type => ::Thrift::Types::I32, :name => 'b'},
      C => {:type => ::Thrift::Types::I32, :name => 'c'},
      D => {:type => ::Thrift::Types::I32, :name => 'd'},
      E => {:type => ::Thrift::Types::I32, :name => 'e'},
      F => {:type => ::Thrift::Types::I32, :name => 'f'},
      G => {:type => ::Thrift::Types::I32, :name => 'g'},
      H => {:type => ::Thrift::Types::I32, :name => 'h'},
      I => {:type => ::Thrift::Types::I32, :name => 'i'},
      J => {:type => ::Thrift::Types::I32, :name => 'j'},
      K => {:type => ::Thrift::Types::I32, :name => 'k'},
      L => {:type => ::Thrift::Types::I32, :name => 'l'},
      M => {:type => ::Thrift::Types::I32, :name => 'm'},
      N => {:type => ::Thrift::Types::I32, :name => 'n'},
      O => {:type => ::Thrift::Types::STRING, :name => 'o'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end
end
