#
# Autogenerated by Thrift Compiler (0.1.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
# Generated with:
#
# ./sparsam-gen -o . ../thrift/order.thrift
#
# Scoped to a module to isolate from other benchmarks

require 'sparsam'

module Sparsam
  class Order < ::Sparsam::Struct
    FIELDS = {
      1 => {:type => ::Sparsam::Types::I32, :name => 'a'},
      2 => {:type => ::Sparsam::Types::I32, :name => 'b'},
      3 => {:type => ::Sparsam::Types::I32, :name => 'c'},
      4 => {:type => ::Sparsam::Types::I32, :name => 'd'},
      5 => {:type => ::Sparsam::Types::I32, :name => 'e'},
      6 => {:type => ::Sparsam::Types::I32, :name => 'f'},
      7 => {:type => ::Sparsam::Types::I32, :name => 'g'},
      8 => {:type => ::Sparsam::Types::I32, :name => 'h'},
      9 => {:type => ::Sparsam::Types::I32, :name => 'i'},
      10 => {:type => ::Sparsam::Types::I32, :name => 'j'},
      11 => {:type => ::Sparsam::Types::I32, :name => 'k'},
      12 => {:type => ::Sparsam::Types::I32, :name => 'l'},
      13 => {:type => ::Sparsam::Types::I32, :name => 'm'},
      14 => {:type => ::Sparsam::Types::I32, :name => 'n'},
      15 => {:type => ::Sparsam::Types::STRING, :name => 'o'}
    }

    init_thrift_struct(self)
  end
end
