# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Order" do
    optional :a, :int32, 1
    optional :b, :int32, 2
    optional :c, :int32, 3
    optional :d, :int32, 4
    optional :e, :int32, 5
    optional :f, :int32, 6
    optional :g, :int32, 7
    optional :h, :int32, 8
    optional :i, :int32, 9
    optional :j, :int32, 10
    optional :k, :int32, 11
    optional :l, :int32, 12
    optional :m, :int32, 13
    optional :n, :int32, 14
    optional :o, :string, 15
  end
end

ProtoOrder = Google::Protobuf::DescriptorPool.generated_pool.lookup("Order").msgclass
